### ISSUE TITLE
[localize] Create localized phrase definitions

### ISSUE THREAD

**Issue by ianb** [mozilla/firefox-voice#1013]
Once #1012 is done, we'll want to create new phrases in other languages.

I think the best way would be to put them in the existing `.toml` files. So for instance we have:

```toml
[clipboard.copyLink]
description = "Copies the link of the current tab"
match = """
  copy (the |) (this |) (tab's |) (link | url) (of this tab |) (to clipboard |)
"""

[[clipboard.copyLink.example]]
phrase = "Copy link"
```

And maybe we'd add (pardon my translation):

```toml
[es.clipboard.copyLink]
description = "Copia el enlace de la pestaña actual"
match = """
  copia (el |) enlace (de |) (la |) (pestaña |)
"""

[[es.clipboard.copyLink.example]]
phrase = "Copia el enlace"
```

Then in [parse-intent-toml.js](https://github.com/mozilla/firefox-voice/blob/master/bin/parse-intent-toml.js) we'd fix this up into... something appropriate. For TOML I think using a prefix for the language is easiest, it may or may not be the right approach for the compiled JSON.

Then of course we should use the appropriate phrase language when matching intents and getting examples.
